server:
  port: 8080

spring:
  application:
    name: ingestor

  datasource:
    url: jdbc:postgresql://localhost:5432/pulseops_db
    username: pulseops
    password: qpalzm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer