server:
  port: 8081

spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/pulseops_db?TimeZone=Asia/Kolkata
    username: pulseops
    password: qpalzm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pulseops-ai-fresh-start
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      poll-timeout: 600000

gemini:
  api:
    key: AQ.Ab8RN6Isn5sZh0RUpQ6rGfiDr1fs-Ba6Z4IIUREfpdSyIdH9Vw
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent