import { CircleAlert, RefreshCw, Sparkles } from 'lucide-react'
import { Button } from '../../components/Button'
import { Spinner } from '../../components/Spinner'

export function AnalysisPanel({ analysis, onRetry, isRetrying }) {
  return (
    <section className="card p-4" aria-labelledby="analysis-title">
      <div className="mb-3 flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-purple-400" aria-hidden="true" />
        <h2 id="analysis-title" className="text-sm font-semibold text-zinc-100">
          AI analysis
        </h2>
      </div>
      <AnalysisBody analysis={analysis} onRetry={onRetry} isRetrying={isRetrying} />
    </section>
  )
}

function AnalysisBody({ analysis, onRetry, isRetrying }) {
  if (!analysis) {
    return <p className="text-sm text-muted">No AI analysis is available for this incident.</p>
  }

  switch (analysis.status) {
    case 'PENDING':
      return (
        <div className="py-6 text-purple-300">
          <Spinner label="Analyzing…" />
        </div>
      )
    case 'DISABLED':
      return <p className="text-sm text-muted">AI analysis is not configured on this server.</p>
    case 'FAILED':
      return (
        <div className="space-y-3">
          <div role="alert" className="flex gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-300">
            <CircleAlert className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
            <span>{analysis.error || 'The analysis failed.'}</span>
          </div>
          <Button size="sm" icon={RefreshCw} onClick={onRetry} isLoading={isRetrying}>
            Retry analysis
          </Button>
        </div>
      )
    case 'COMPLETED':
      return <CompletedAnalysis analysis={analysis} />
    default:
      return null
  }
}

function CompletedAnalysis({ analysis }) {
  const confidence = Math.max(0, Math.min(100, analysis.confidence ?? 0))
  const actions = analysis.suggestedActions ?? []

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-xs font-medium uppercase tracking-wide text-subtle">Probable root cause</h3>
        <p className="mt-1 whitespace-pre-line text-sm leading-relaxed text-zinc-200">{analysis.rootCause}</p>
      </div>

      <div>
        <div className="mb-1 flex justify-between text-xs">
          <span className="font-medium uppercase tracking-wide text-subtle">Confidence</span>
          <span className="tabular-nums text-zinc-300">{confidence}%</span>
        </div>
        <div
          className="h-1.5 overflow-hidden rounded-full bg-zinc-800"
          role="meter"
          aria-label="Confidence"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={confidence}
        >
          <div className="h-full rounded-full bg-purple-400" style={{ width: `${confidence}%` }} />
        </div>
      </div>

      {actions.length > 0 && (
        <div>
          <h3 className="text-xs font-medium uppercase tracking-wide text-subtle">Suggested actions</h3>
          <ol className="mt-2 list-decimal space-y-1.5 pl-5 text-sm text-zinc-200 marker:text-subtle">
            {actions.map((action, index) => (
              <li key={index}>{action}</li>
            ))}
          </ol>
        </div>
      )}

      <p className="flex flex-wrap gap-x-2 border-t border-line pt-3 text-xs text-subtle">
        <span className="font-medium text-amber-300/90">AI suggestion — verify before acting</span>
        {analysis.model && <span>· Generated by {analysis.model}</span>}
      </p>
    </div>
  )
}
